[package]
name = "ultrawm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ultrawm"
path = "src/main.rs"

[dependencies]
ultrawm-core = { path = "../lib/ultrawm-core" }
ctrlc = "3.4"
tray-icon = "0.14"
resvg = "0.37"
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4"
colored = "2.1"
